#! /usr/bin/env python
import time

import gevent.monkey
gevent.monkey.patch_all()
import cubi.proxy as proxy
import cubi.logger as logger

if __name__ == '__main__':
    logger.enable_debug_log()
    endp = 'cmd@tcp::2017'
    print 'start test for ', endp
    prx = proxy.Proxy(endp, True)

    data = {'cmd': 'ls -l'}
    r = prx.request('run', data)
    print r['data']
